name: Test Retry Logic

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  test-retry:
    runs-on: ubuntu-latest

    env:
      RETRY_COUNT: 0 # Initialize the retry count

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Retry Logic
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 5
          shell: bash
          command: |
            echo "Current retry count: $RETRY_COUNT"
            if [ "$RETRY_COUNT" -lt 5 ]; then
              export RETRY_COUNT=$((RETRY_COUNT + 1))
              echo "Retry count updated to $RETRY_COUNT"
              exit 1
            else
              echo "Success on attempt $RETRY_COUNT"
              exit 0
            fi
